---
title: "Visualizations For Project"
author: "Steve Phillips"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Import necessary libraries
library(readr)
library(tidyverse)
library(stringr)
library(dplyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
```
```{r}
##Load Datasets
coinbase <- read_csv("https://raw.githubusercontent.com/sphill12/Project_3_Data_607/main/coinbase_daily_data.csv")
ftx <- read_csv("https://raw.githubusercontent.com/sphill12/Project_3_Data_607/main/ftx_daily_data.csv")
layer_one <- read_csv("https://raw.githubusercontent.com/sphill12/Project_3_Data_607/main/layer_one_daily_data.csv")
```
```{r}

```


```{r}
## Add a percent change column, to determine volatile months
ftx <- ftx %>% mutate(percent_change = (((close - open)/open)*100))
coinbase <- coinbase %>% mutate(percent_change = (((close - open)/open)*100))
layer_one <- layer_one %>% mutate(percent_change = (((close - open)/open)*100))
```
```{r}

```


```{r}
## remove high and low columns as they won't be used in analysis
ftx <- subset(ftx, select = -c(high, low))
coinbase <- subset(coinbase, select = -c(high, low))
layer_one <- subset(layer_one, select = -c(high, low))

```


```{r}
unique(layer_one$coin)
```
```{r}
unique(ftx$coin)
```
```{r}
unique(coinbase$coin)
```
```{r}
layer_one %>% filter(coin == "SOL")
```

```{r}
layer_one %>% filter(date > "2020-04-01") %>% filter(coin == "SEI")
```


```{r}
##To determine correlation, I have pivoted the dataframe to be wide
wide_layer_one <- subset(layer_one, select = -c(...1, open,close, volume,marketcap))
wide_layer_one <- pivot_wider(wide_layer_one, names_from = coin, values_from = percent_change)
```
```{r}
print(wide_layer_one, n=2000000)
```

```{r}
## Due to gaps in the dates of data available to us, correlation in one large matrix is not possible. Correlation between specific pairs is fine however
first_pairs <- wide_layer_one %>% arrange(date)
## Drop the date, as it isn't necessary for correlation
first_pairs <- first_pairs[,-1]
```
```{r}
first_pairs %>% drop_na()
```




```{r}
## Correlation of layer 1 coins
corr <- round(cor(first_pairs %>% drop_na()),10)
```
```{r}
corr_df <- as.data.frame(corr)
corr_df[corr_df < 0.7] <- ""

corr_df_2 <- as.matrix(corr_df)
```
```{r}
corr_coins <- layer_one %>% filter(coin %in% c("ADA", "ALGO","APT", "AVAX","CHZ","DOT","EGLD","ETH","FTM","SOL","BNB","XTZ"))
wide_coins_of_interest <- subset(corr_coins, select = -c(...1, open,close, volume,marketcap))
wide_coins_of_interest <- pivot_wider(wide_coins_of_interest, names_from = coin, values_from = percent_change)
wide_coins_of_interest <- wide_coins_of_interest[,-1]
high_corr <- round(cor(wide_coins_of_interest %>% drop_na()),10)
```
```{r}
ggcorrplot(high_corr, 
           hc.order = TRUE, 
           type = "lower", 
           lab= TRUE, 
           lab_size = 3, 
           method = "circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title = "Corellation of Daily Returns ", 
           ggtheme = theme_bw)
```


```{r}
corr_df
```

```{r}
ggcorrplot(corr_df_2, hc.order = TRUE, type = "lower",
           lab = TRUE)
```


```{r}
filtered_corr <- corr[corr > 0.2]
```
```{r}
filtered_corr
```


```{r}

ggcorrplot(corr_df, 
           hc.order = TRUE, 
           type = "lower", 
           lab= TRUE, 
           lab_size = 3, 
           method = "circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title = "Corellation of Monthly Returns ", 
           ggtheme = theme_bw)
```
## Most Layer ones have positive correlation with eachother. Eth is the largest marketcap layer one, and it seems that other smaller layer ones move in conjunction with it. Of these coins, Aptos and BCH have the least amount of correlation with monthly returns.
```{r}
second_pairs <- wide_layer_one %>% select(timestamp, SOL,RXD, XEC,XRD,KDA,KAS,HBAR,FUSE,FTM,FLOW,EGLD,DOT,CHZ, CCD,ALGO) %>% arrange(timestamp) %>% na.exclude()
second_pairs <- second_pairs[,-1]
```
```{r}
second_pairs
```

```{r}
corr2 <- round(cor(second_pairs),3)
ggcorrplot(corr2, 
           hc.order = TRUE, 
           type = "lower", 
           lab= TRUE, 
           lab_size = 3, 
           method = "circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title = "Corellation of Monthly Returns ", 
           ggtheme = theme_bw)
```
```{r}
## We can see that there are some outliers. Lets filter to see when this occurred
layer_one %>% ggplot(aes(x = timestamp, y = percent_change, color = coin)) + geom_point()
```
```{r}
## We can see that ADA,BNB, CHZ, ERG, FUSE, KAS have all had returns that are over 250%
layer_one %>% filter(percent_change > 250)
```
```{r}
layer_one_stats <- layer_one %>% group_by(coin)%>% summarize(standard_deviation = sd(percent_change), mean = mean(percent_change), variance = var(percent_change))
```
```{r}
## We can see that the percent returns of one of the most established coins follows a normal distribution.The distribution of ethereum is skewed to the left however. Negative events are more extreme than positive events when it comes to crypto currencies 
layer_one %>% filter(coin == "ETH") %>% ggplot(aes(x = percent_change)) +
        geom_blank() +
        geom_histogram(aes(y = ..density..)) +
        stat_function(fun = dnorm, args = c(mean = 0.18197130, sd = 4.783556), col = "tomato")
```
```{r}
##ERG contains the largest outliers for percent returns
layer_one %>% 
  ggplot(aes(x = coin, y = percent_change)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  ylab("Percent Change") +
  xlab("Coin") + 
  ggtitle("Box Plot of Percent Return of Layer One Coins")
```
```{r}
## Compared to ETH, ERG has a rightward skew
layer_one %>% filter(coin == "ERG") %>% ggplot(aes(x = percent_change)) +
        geom_blank() +
        geom_histogram(aes(y = ..density..)) +
        stat_function(fun = dnorm, args = c(mean = 0.79755294	, sd = 16.115026	), col = "tomato")
```

```{r}
ftx %>%
  ggplot(aes(x  = coin, y = percent_change)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  ylab("Percent Change") +
  xlab("Coin") +
  ggtitle("Box Plot of Percent Return of FTX Coin Portfolio")
```
```{r}
##Interestingly coinbase has a larger spread in data values
coinbase %>%
  ggplot(aes(x  = coin, y = percent_change)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  ylab("Percent Change") +
  xlab("Coin") +
  ggtitle("Box Plot of Percent Return of Coin Base Coin Portfolio")
```
```{r}
coinbase %>% filter(coin == "LUNC") %>% ggplot(aes(x = percent_change)) +
        geom_blank() +
        geom_histogram(aes(y = ..density..)) +
        stat_function(fun = dnorm, args = c(mean = 0.79755294	, sd = 16.115026	), col = "tomato")
```




```{r}
## Visualize coinbase
coinbase %>% group_by(coin) %>% ggplot(aes(x = date, y = percent_change, color = coin)) + geom_point() + ylim(-400, 400)
```


















